export enum SystemAction {
  MEMBERSHIP_APPROVED = 'MEMBERSHIP_APPROVED',
  MEMBERSHIP_REJECTED = 'MEMBERSHIP_REJECTED',
  ACCOUNT_ACTIVATED = 'ACCOUNT_ACTIVATED',
  ACCOUNT_INACTIVATED = 'ACCOUNT_INACTIVATED',
  ACCOUNT_DELETED = 'ACCOUNT_DELETED',
  ROLE_CHANGED = 'ROLE_CHANGED',
  DIRECTOR_BOARD_CREATED = 'DIRECTOR_BOARD_CREATED',
  DIRECTOR_BOARD_DELETED = 'DIRECTOR_BOARD_DELETED',
  ADMIN_ROLE_TRANSFERRED = 'ADMIN_ROLE_TRANSFERRED',
}
