/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  auth: {
    AccessTokens: () => import('#controllers/auth/access_tokens_controller'),
    AllSessions: () => import('#controllers/auth/all_sessions_controller'),
    ForgotPassword: () => import('#controllers/auth/forgot_password_controller'),
    RefreshTokens: () => import('#controllers/auth/refresh_tokens_controller'),
    ResetPassword: () => import('#controllers/auth/reset_password_controller'),
    Sessions: () => import('#controllers/auth/sessions_controller'),
  },
  mediaAsset: {
    MediaAssets: () => import('#controllers/media_asset/media_assets_controller'),
  },
  missionary: {
    About: () => import('#controllers/missionary/about_controller'),
    Identity: () => import('#controllers/missionary/identity_controller'),
    Profile: () => import('#controllers/missionary/profile_controller'),
    WorkAddress: () => import('#controllers/missionary/work_address_controller'),
  },
  user: {
    Account: () => import('#controllers/user/account_controller'),
    AccountPassword: () => import('#controllers/user/account_password_controller'),
    Profile: () => import('#controllers/user/profile_controller'),
    UsernameAvailability: () => import('#controllers/user/username_availability_controller'),
  },
}
