/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

import AuthLoginAttempted from '#events/auth/login_attempted'
import AuthPasswordResetRequested from '#events/auth/password_reset_requested'
import UserUserRegistered from '#events/user/user_registered'

export const events = {
  auth: {
    LoginAttempted: AuthLoginAttempted,
    PasswordResetRequested: AuthPasswordResetRequested,
  },
  user: {
    UserRegistered: UserUserRegistered,
  },
}
