/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

import AuthLoginAttempted from '#events/auth/login_attempted'
import AuthPasswordResetRequested from '#events/auth/password_reset_requested'
import FollowerUserFollowed from '#events/follower/user_followed'
import FollowerUserUnfollowed from '#events/follower/user_unfollowed'
import MissionaryMissionaryProfileCreated from '#events/missionary/missionary_profile_created'
import UserUserRegistered from '#events/user/user_registered'

export const events = {
  auth: {
    LoginAttempted: AuthLoginAttempted,
    PasswordResetRequested: AuthPasswordResetRequested,
  },
  follower: {
    UserFollowed: FollowerUserFollowed,
    UserUnfollowed: FollowerUserUnfollowed,
  },
  missionary: {
    MissionaryProfileCreated: MissionaryMissionaryProfileCreated,
  },
  user: {
    UserRegistered: UserUserRegistered,
  },
}
