/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = [
    'abilities',
    'createdAt',
    'expiresAt',
    'hash',
    'id',
    'lastUsedAt',
    'name',
    'tokenableId',
    'type',
    'updatedAt',
  ] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class AuthenticationAuditSchema extends BaseModel {
  static $columns = [
    'browser',
    'createdAt',
    'id',
    'ipAddress',
    'remotePort',
    'status',
    'userAgent',
    'userId',
  ] as const
  $columns = AuthenticationAuditSchema.$columns
  @column()
  declare browser: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare ipAddress: string | null
  @column()
  declare remotePort: string | null
  @column()
  declare status: string
  @column()
  declare userAgent: string | null
  @column()
  declare userId: string | null
}

export class CampaignProjectSchema extends BaseModel {
  static $columns = ['campaignId', 'createdAt', 'id', 'projectId'] as const
  $columns = CampaignProjectSchema.$columns
  @column()
  declare campaignId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare projectId: string
}

export class CampaignSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'endDate',
    'id',
    'isActive',
    'name',
    'startDate',
    'suspendedAt',
  ] as const
  $columns = CampaignSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare endDate: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isActive: boolean
  @column()
  declare name: string
  @column.dateTime()
  declare startDate: DateTime | null
  @column.dateTime()
  declare suspendedAt: DateTime | null
}

export class CommentSchema extends BaseModel {
  static $columns = ['content', 'createdAt', 'id', 'postId', 'updatedAt', 'userId'] as const
  $columns = CommentSchema.$columns
  @column()
  declare content: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare postId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
}

export class FaithCommunitySchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'phoneNumber', 'userId'] as const
  $columns = FaithCommunitySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare phoneNumber: string
  @column()
  declare userId: string | null
}

export class FinancialConfigSchema extends BaseModel {
  static $columns = [
    'accountNumber',
    'accountType',
    'agency',
    'bankName',
    'bankNumber',
    'createdAt',
    'holderDocument',
    'holderName',
    'id',
    'missionaryId',
    'pixKey',
    'qrCodeAssetId',
    'updatedAt',
  ] as const
  $columns = FinancialConfigSchema.$columns
  @column()
  declare accountNumber: string | null
  @column()
  declare accountType: string | null
  @column()
  declare agency: string | null
  @column()
  declare bankName: string | null
  @column()
  declare bankNumber: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare holderDocument: string | null
  @column()
  declare holderName: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare missionaryId: string
  @column()
  declare pixKey: string | null
  @column()
  declare qrCodeAssetId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class FollowerSchema extends BaseModel {
  static $columns = ['createdAt', 'followerId', 'followingId', 'id'] as const
  $columns = FollowerSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare followerId: string
  @column()
  declare followingId: string
  @column({ isPrimary: true })
  declare id: string
}

export class ImpactProjectSchema extends BaseModel {
  static $columns = [
    'coverImageAssetId',
    'createdAt',
    'description',
    'id',
    'missionaryId',
    'title',
    'updatedAt',
    'videoAssetId',
  ] as const
  $columns = ImpactProjectSchema.$columns
  @column()
  declare coverImageAssetId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare missionaryId: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare videoAssetId: string | null
}

export class LikeSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'postId', 'userId'] as const
  $columns = LikeSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare postId: string
  @column()
  declare userId: string
}

export class MediaAssetSchema extends BaseModel {
  static $columns = [
    'bucket',
    'createdAt',
    'fileKey',
    'fileSizeBytes',
    'id',
    'mimeType',
    'provider',
  ] as const
  $columns = MediaAssetSchema.$columns
  @column()
  declare bucket: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare fileKey: string
  @column()
  declare fileSizeBytes: number
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare mimeType: string
  @column()
  declare provider: string
}

export class MissionarySchema extends BaseModel {
  static $columns = [
    'createdAt',
    'donationMessage',
    'id',
    'identityDocument',
    'identityType',
    'missionaryAgencyId',
    'publicEmail',
    'publicPhone',
    'status',
    'userId',
  ] as const
  $columns = MissionarySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare donationMessage: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare identityDocument: string | null
  @column()
  declare identityType: string | null
  @column()
  declare missionaryAgencyId: string
  @column()
  declare publicEmail: string | null
  @column()
  declare publicPhone: string | null
  @column()
  declare status: string
  @column()
  declare userId: string
}

export class MissionaryAgencySchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'phoneNumber', 'userId'] as const
  $columns = MissionaryAgencySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare phoneNumber: string | null
  @column()
  declare userId: string | null
}

export class MissionaryWorkAddressSchema extends BaseModel {
  static $columns = [
    'city',
    'country',
    'createdAt',
    'district',
    'id',
    'missionaryId',
    'state',
    'zip',
  ] as const
  $columns = MissionaryWorkAddressSchema.$columns
  @column()
  declare city: string
  @column()
  declare country: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare district: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare missionaryId: string
  @column()
  declare state: string
  @column()
  declare zip: string
}

export class PastorSchema extends BaseModel {
  static $columns = ['createdAt', 'faithCommunityId', 'fullName', 'id', 'phoneNumber'] as const
  $columns = PastorSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare faithCommunityId: string
  @column()
  declare fullName: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare phoneNumber: string
}

export class PostImageSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'imageAssetId', 'order', 'postId'] as const
  $columns = PostImageSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare imageAssetId: string
  @column()
  declare order: number
  @column()
  declare postId: string
}

export class PostSchema extends BaseModel {
  static $columns = ['content', 'createdAt', 'highlightLink', 'id', 'missionaryId', 'slug'] as const
  $columns = PostSchema.$columns
  @column()
  declare content: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare highlightLink: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare missionaryId: string
  @column()
  declare slug: string
}

export class RedirectSchema extends BaseModel {
  static $columns = ['createdAt', 'destinationPath', 'id', 'sourcePath', 'statusCode'] as const
  $columns = RedirectSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare destinationPath: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare sourcePath: string
  @column()
  declare statusCode: number
}

export class UserActionAuditSchema extends BaseModel {
  static $columns = [
    'actionType',
    'actorId',
    'createdAt',
    'id',
    'ipAddress',
    'metadata',
    'targetId',
  ] as const
  $columns = UserActionAuditSchema.$columns
  @column()
  declare actionType: string
  @column()
  declare actorId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare ipAddress: string | null
  @column()
  declare metadata: any | null
  @column()
  declare targetId: string | null
}

export class UserSchema extends BaseModel {
  static $columns = [
    'activedAt',
    'biography',
    'createdAt',
    'deletedAt',
    'email',
    'emailVerifiedAt',
    'followersCount',
    'followingCount',
    'fullName',
    'gender',
    'id',
    'lastLogin',
    'loginAttempts',
    'membershipStatus',
    'passwordHash',
    'pendingEmail',
    'pendingEmailToken',
    'pendingEmailTokenExpiresAt',
    'phoneNumber',
    'profilePictureId',
    'recoveryPasswordToken',
    'recoveryPasswordTokenExpiresAt',
    'role',
    'updatedAt',
    'username',
  ] as const
  $columns = UserSchema.$columns
  @column.dateTime()
  declare activedAt: DateTime | null
  @column()
  declare biography: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare email: string
  @column.dateTime()
  declare emailVerifiedAt: DateTime | null
  @column()
  declare followersCount: number
  @column()
  declare followingCount: number
  @column()
  declare fullName: string | null
  @column()
  declare gender: string
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare lastLogin: DateTime | null
  @column()
  declare loginAttempts: number
  @column()
  declare membershipStatus: string
  @column()
  declare passwordHash: string
  @column()
  declare pendingEmail: string | null
  @column()
  declare pendingEmailToken: string | null
  @column.dateTime()
  declare pendingEmailTokenExpiresAt: DateTime | null
  @column()
  declare phoneNumber: string
  @column()
  declare profilePictureId: string | null
  @column()
  declare recoveryPasswordToken: string | null
  @column.dateTime()
  declare recoveryPasswordTokenExpiresAt: DateTime | null
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare username: string
}
