/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type SessionTransformer from '#transformers/session_transformer'
import type UserTransformer from '#transformers/user_transformer'

export namespace Data {
  export type Session = InferData<SessionTransformer>
  export namespace Session {
    export type Variants = InferVariants<SessionTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
}
